package by.wolearn.core


object BackendErrors {

    const val LOGIN_ERROR_1 = "AUTH000"
    const val PASSWORD_ERROR_1 = "AUTH001"
    const val PASSWORD_ERROR_2 = "AUTH002"
    const val PASSWORD_ERROR_3 = "AUTH006"

    const val REGISTER_NAME_ERROR_1 = "AUTH003"
    const val REGISTER_SURNAME_ERROR_1 = "AUTH004"

    const val WORDINSERT_WORD_ERROR_1 = "WORDINS001"
    const val WORDINSERT_TRANSCRIPTION_ERROR_2 = "WORDINS002"
    const val WORDINSERT_POS_ERROR_3 = "WORDINS003"
    const val WORDINSERT_CATEGORY_ERROR_4 = "WORDINS004"
    const val WORDINSERT_EXAMPLES_ERROR_5 = "WORDINS005"
    const val WORDINSERT_QUIZ_ERROR_6 = "WORDINS006"

}